### ISSUE TITLE
DataSourceUpdateDelegate functions could be consolidated?

### ISSUE THREAD

**Issue by JosephDuffy** [shaps80/Composed#3]
While trying to get `ComposedDataSource` to work I noticed that the methods on `DataSourceUpdateDelegate` seem to be somewhat duplicated.

At first I had assumed that I should use `func dataSource(_ dataSource: DataSource, willPerform updates: [DataSourceUpdate])` and `func dataSource(_ dataSource: DataSource, didPerform updates: [DataSourceUpdate])`, but then I noticed the `func dataSource(_ dataSource: DataSource, did*)` functions.

Looking at `DataSourceUpdate` it has equivalents for each of the `func dataSource(_ dataSource: DataSource, did*)` functions. Do these have explicit different uses, or could they be consolidated? I saw that in `CollectionViewWrapper` both functions are handled, but in the `func dataSource(_ dataSource: DataSource, did*)` functions the messages are passed to the collection view, but in `func dataSource(_ dataSource: DataSource, didPerform updates: [DataSourceUpdate])` only the placeholder is updated.

Using only the `DataSourceUpdate` methods would maybe make implementations smaller (e.g. the message passing in `SegmentedDataSource` would be much smaller), and would IMO be the better solution.

What do you think?

**Comment by shaps80** [comment]
I actually have a new solution which would reduce all delegate functions into a single method. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by shaps80** [comment]
I’ll post it as a PR shortly and you can review. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by shaps80** [comment]
Included in PR #5
